//! Helper traits used by the widget derive macros.
//!
//! The derive macros in `plushie-core-macros` (`#[derive(WidgetEvent)]`,
//! `#[derive(WidgetCommand)]`, `#[derive(WidgetProps)]`) expand to
//! code that calls these traits. App code typically does not reference
//! them directly; they exist so the generated code has stable names
//! to bind against.
//!
//! This module is always available (including in wire-only builds)
//! because app-level derive expansions compile in every feature
//! configuration.

/// Decode a widget prop struct from a [`TreeNode`](plushie_core::protocol::TreeNode).
///
/// Generated by `#[derive(WidgetProps)]`.
pub use plushie_core::types::FromNode;

/// Wire encode/decode for plushie domain types.
///
/// Used by the widget-event and widget-command encoders to serialize
/// typed enum payloads.
pub use plushie_core::types::PlushieType;

/// Encoder trait for widget event enums.
///
/// Generated by `#[derive(WidgetEvent)]`.
pub use plushie_core::types::WidgetEventEncode;

/// Encoder trait for widget command enums.
///
/// Generated by `#[derive(WidgetCommand)]`.
pub use plushie_core::spec::WidgetCommandEncode;
