//! Tree normalization: scope prefixing, ID validation, a11y rewrites.
//!
//! After `App::view()` returns a `View` (TreeNode), normalization
//! walks the tree to apply scoped ID prefixes and validate ID
//! constraints. A second pass rewrites cross-widget accessibility
//! references (`labelled_by`, `described_by`, `error_message`,
//! `active_descendant`, `radio_group`) through the same scope-
//! prefix logic, populates implicit radio groups from the shared
//! `group` prop on radios, and fills in the accessible role from
//! the widget type when the author did not set one.
//!
//! ## Scoping rules
//!
//! Containers with explicit (non-auto) IDs create a scope. Their
//! children's IDs are prefixed with the scope chain joined by `/`.
//! Two node types are exempt:
//!
//! - **Auto IDs** (prefixed `auto:`): generated by the DSL, not
//!   user-chosen. They don't participate in scoping and bypass
//!   duplicate detection (the same call site in a loop produces
//!   identical auto IDs).
//! - **Window nodes** (`type_name == "window"`): top-level layout
//!   containers that don't scope their children.
//!
//! ## ID constraints
//!
//! - `/` is reserved as the scope separator and rejected in
//!   user-provided IDs.
//! - Duplicate explicit IDs within a tree produce a warning.
//!
//! ## Depth cap
//!
//! Recursion is capped at
//! [`plushie_widget_sdk::shared_state::MAX_TREE_DEPTH`]. Beyond the
//! cap the subtree is truncated (the returned node has no children)
//! and a `tree_too_deep` diagnostic is appended. Render and
//! prepare_walk apply the same cap so defence-in-depth holds even
//! if the host sends a pathologically nested tree.
//!
//! ## A11y rewrites
//!
//! Cross-widget references inside the `a11y` prop are scope-rewritten
//! the same way widget IDs are: a reference to `heading` inside a
//! scoped `form` container becomes `main#form/heading`. References
//! that cannot be resolved to any declared ID in the normalized
//! tree produce an `a11y_ref_unresolved` diagnostic.
//!
//! Radio widgets sharing the same `group` prop value are collected
//! into an implicit radio group: each member's `a11y.radio_group` is
//! populated with the scoped IDs of its peers. This mirrors the
//! HTML `<input type="radio" name="x">` model where grouping is by
//! name, not DOM position.
//!
//! `a11y.role` is auto-populated from the widget type when the
//! author has not set one. `automation::Element::inferred_role`
//! reads this normalized prop directly.

use std::collections::{BTreeMap, HashSet};

use plushie_core::protocol::{PropValue, TreeNode};
#[cfg(any(test, feature = "wire"))]
use plushie_core::tree_walk::walk;
use plushie_core::tree_walk::{MAX_TREE_DEPTH, TreeTransform, WalkCtx};

/// Normalize a view tree: apply scope prefixes, validate IDs,
/// rewrite cross-widget a11y references, and auto-populate a11y
/// defaults (role, radio_group).
///
/// Returns the normalized tree and any validation warnings
/// (duplicate IDs, reserved characters, unresolved a11y refs).
///
/// Thin wrapper around the `NormalizeTransform`: drives it through
/// `walk()` over a clone of the input, then runs the cross-widget
/// a11y passes. Call sites that already own a mutable tree can
/// compose [`NormalizeTransform`] with other transforms through
/// `walk()` directly and then invoke [`finalize_a11y`].
#[cfg(any(test, feature = "wire"))]
pub fn normalize(tree: &TreeNode) -> (TreeNode, Vec<String>) {
    let mut result = tree.clone();
    let mut transform = NormalizeTransform::new();
    let mut ctx = WalkCtx::default();
    walk(&mut result, &mut [&mut transform], &mut ctx);
    let (warnings, _ctx) = finalize_a11y(&mut result, ctx);
    (result, warnings)
}

/// Run the a11y-ref rewrite and missing-accessible-name passes over a
/// tree whose IDs are already scope-normalized. Continues accumulating
/// warnings into the supplied [`WalkCtx`].
///
/// Split from `normalize_in_place` so callers that compose
/// normalization with other transforms in a single traversal can still
/// reuse the cross-widget a11y logic, which has to run *after* the
/// full set of declared IDs is known.
pub(crate) fn finalize_a11y(tree: &mut TreeNode, mut ctx: WalkCtx) -> (Vec<String>, WalkCtx) {
    let declared_ids = collect_ids(tree);
    let radio_groups = collect_radio_groups(tree);
    rewrite_a11y_in_place(tree, "", &declared_ids, &radio_groups, &mut ctx.warnings, 0);
    check_missing_accessible_name(tree, &mut ctx.warnings);

    let warnings = std::mem::take(&mut ctx.warnings);
    (warnings, ctx)
}

/// First-pass transform: scope-rewrite IDs, detect duplicates and
/// reserved characters, cap recursion depth.
///
/// Uses `WalkCtx::scope` as a stack: `enter` extends it with this
/// node's contribution; `exit` truncates back to the pre-enter length.
/// Normalize-specific state (duplicate-ID set, depth counter) stays
/// inside the transform so `WalkCtx` can remain scope-only.
pub(crate) struct NormalizeTransform<'a> {
    seen_ids: HashSet<String>,
    /// Length to truncate `ctx.scope` to on `exit` for each node on
    /// the stack. Mirrors the recursion frames.
    scope_stack: Vec<usize>,
    /// Per-node truncation flag. Non-empty at a cache hit so `exit`
    /// knows not to store back into the memo cache when the subtree
    /// was served from the cache rather than freshly walked.
    truncate_children: Vec<bool>,
    /// Per-node memo state: if the node was a memo hit we suppress
    /// descent and skip writing back to the cache; if it was a miss
    /// we stash the (scoped_id, deps_hash) so `exit` can store the
    /// freshly-normalized children. `None` for non-memo nodes.
    memo_stack: Vec<Option<MemoFrame>>,
    /// Optional memo cache. `None` disables memoization entirely.
    memo_cache: Option<&'a mut super::memo_cache::MemoCache>,
}

/// Per-memo-node state pushed onto `memo_stack`. On cache hit, the
/// `was_hit` flag keeps `exit` from re-storing the (unchanged)
/// subtree; on miss, `deps_hash` is stored alongside the scoped id
/// so the new normalized children can be cached.
struct MemoFrame {
    scoped_id: String,
    deps_hash: u64,
    was_hit: bool,
}

impl<'a> NormalizeTransform<'a> {
    #[cfg(any(test, feature = "wire"))]
    pub(crate) fn new() -> Self {
        Self::with_memo_cache(None)
    }

    pub(crate) fn with_memo_cache(
        memo_cache: Option<&'a mut super::memo_cache::MemoCache>,
    ) -> Self {
        Self {
            seen_ids: HashSet::new(),
            scope_stack: Vec::new(),
            truncate_children: Vec::new(),
            memo_stack: Vec::new(),
            memo_cache,
        }
    }
}

impl TreeTransform for NormalizeTransform<'_> {
    fn enter(&mut self, node: &mut TreeNode, ctx: &mut WalkCtx) {
        // Depth enforcement lives in `plushie_core::tree_walk::walk`,
        // which halts descent at MAX_TREE_DEPTH and pushes a
        // `tree_depth_exceeded` warning. We still run scope/memo
        // bookkeeping here so `exit` restores state symmetrically.

        // Snapshot where the enclosing scope ended so `exit` can
        // restore `ctx.scope` to exactly this length.
        let prev_scope_len = ctx.scope.len();
        let type_name = &node.type_name;
        let is_auto = node.id.starts_with("auto:");
        let is_window = type_name == "window";

        // Reserved-character validation (user IDs only). Run before
        // touching `ctx.scope` so diagnostic text references the
        // original ID.
        if !is_auto {
            if node.id.contains('/') {
                ctx.warnings.push(format!(
                    "ID \"{id}\" contains reserved character '/'. \
                     Use container scoping instead.",
                    id = node.id,
                ));
            }
            if node.id.contains('#') {
                ctx.warnings.push(format!(
                    "ID \"{id}\" contains reserved character '#'. \
                     '#' is reserved for window-qualified paths.",
                    id = node.id,
                ));
            }
        }

        // Build the scoped ID directly into `ctx.scope`. The shared
        // buffer is our single scratch allocation for scope paths; we
        // grow it on enter and truncate on exit, so nested levels
        // don't each allocate their own path string.
        //
        // After this block `ctx.scope` equals the child-scope that
        // descendants should see (with the window suffix applied for
        // window nodes).
        let scoped_id = if is_auto || node.id.is_empty() {
            // Auto-IDs and empty IDs never scope-prefix and never
            // contribute to the child-scope path. Leave `ctx.scope`
            // untouched.
            node.id.clone()
        } else if ctx.scope.is_empty() {
            // Top-level node: its ID becomes the root of the scope.
            ctx.scope.push_str(&node.id);
            node.id.clone()
        } else {
            // Nested user-ID: append "/id" unless we're directly under
            // a window boundary ("name#"), in which case the '#' is
            // the separator.
            if !ctx.scope.ends_with('#') {
                ctx.scope.push('/');
            }
            ctx.scope.push_str(&node.id);
            ctx.scope.clone()
        };

        // Duplicate detection (non-auto only). One clone for the
        // HashSet entry.
        if !is_auto && !scoped_id.is_empty() && !self.seen_ids.insert(scoped_id.clone()) {
            ctx.warnings.push(format!("duplicate ID: \"{scoped_id}\""));
        }

        // Windows append a trailing '#' so their children slot in
        // after the window-qualified path (e.g. "main#form").
        if is_window {
            ctx.scope.push('#');
        }

        node.id = scoped_id;

        // Memoization: if this is a __memo__ node and the deps hash
        // matches the cached entry for this scoped id, swap in the
        // cached normalized children and skip descent entirely. On a
        // miss, remember enough state to cache the result on exit.
        let memo_frame = self.consult_memo(node);
        let truncate = memo_frame.as_ref().is_some_and(|f| f.was_hit);

        self.scope_stack.push(prev_scope_len);
        self.truncate_children.push(truncate);
        self.memo_stack.push(memo_frame);
    }

    fn exit(&mut self, node: &mut TreeNode, ctx: &mut WalkCtx) {
        // Pop memo frame first so we know whether to cache on the way
        // out; then restore scope.
        if let Some(Some(frame)) = self.memo_stack.pop() {
            self.finish_memo(node, frame);
        }
        if let Some(prev_len) = self.scope_stack.pop() {
            ctx.scope.truncate(prev_len);
        }
        self.truncate_children.pop();
    }

    fn skip_children(&self, _node: &TreeNode, _ctx: &WalkCtx) -> bool {
        self.truncate_children.last().copied().unwrap_or(false)
    }
}

impl NormalizeTransform<'_> {
    /// Pre-descend memo lookup. Mutates `node.children` in place when
    /// a cache hit installs the previously-normalized subtree. The
    /// returned frame tells `exit` whether to cache the freshly-
    /// walked children.
    fn consult_memo(&mut self, node: &mut TreeNode) -> Option<MemoFrame> {
        if node.type_name != "__memo__" {
            return None;
        }
        let cache = self.memo_cache.as_deref_mut()?;
        // Accept both Typed and Wire props: `get_value` normalises to
        // serde_json::Value so the memo marker works regardless of
        // how the caller built the view tree.
        let deps_hash = node
            .props
            .get_value("__memo_deps__")
            .and_then(|v| v.as_u64())?;

        cache.mark_live(&node.id);

        if let Some(cached) = cache.get(&node.id, deps_hash) {
            node.children = cached.to_vec();
            return Some(MemoFrame {
                scoped_id: node.id.clone(),
                deps_hash,
                was_hit: true,
            });
        }

        Some(MemoFrame {
            scoped_id: node.id.clone(),
            deps_hash,
            was_hit: false,
        })
    }

    /// Post-descend memo cache write. On a miss, stash the freshly-
    /// normalized children. On a hit we have nothing to do - the
    /// cached entry is already what's in `node.children`.
    fn finish_memo(&mut self, node: &TreeNode, frame: MemoFrame) {
        if frame.was_hit {
            return;
        }
        if let Some(cache) = self.memo_cache.as_deref_mut() {
            cache.insert(frame.scoped_id, frame.deps_hash, node.children.clone());
        }
    }
}

// ---------------------------------------------------------------------------
// Pass 2: a11y rewrites
// ---------------------------------------------------------------------------

/// Collect every declared scoped ID in the normalized tree.
fn collect_ids(node: &TreeNode) -> HashSet<String> {
    fn walk(node: &TreeNode, out: &mut HashSet<String>) {
        if !node.id.is_empty() && !node.id.starts_with("auto:") {
            out.insert(node.id.clone());
        }
        for child in &node.children {
            walk(child, out);
        }
    }
    let mut ids = HashSet::new();
    walk(node, &mut ids);
    ids
}

/// Key used to collect radios into a shared group: (enclosing scope, group name).
///
/// Scope is the same scope string we use for IDs; it keeps two radio
/// sets with the same `group` name in separate scoped containers from
/// being lumped together. Window qualifiers are baked into the scope
/// string.
type RadioGroupKey = (String, String);

/// Collect radio widgets sharing the same `group` prop value within
/// the same enclosing scope. Returns a map from `(scope, group_name)`
/// to an ordered list of scoped IDs.
fn collect_radio_groups(root: &TreeNode) -> BTreeMap<RadioGroupKey, Vec<String>> {
    fn walk(node: &TreeNode, scope: &str, groups: &mut BTreeMap<RadioGroupKey, Vec<String>>) {
        let next_scope = child_scope_of(node, scope);
        if node.type_name == "radio"
            && let Some(group) = node.props.get_str("group")
        {
            let key = (scope.to_string(), group.to_string());
            groups.entry(key).or_default().push(node.id.clone());
        }
        for child in &node.children {
            walk(child, &next_scope, groups);
        }
    }
    let mut groups = BTreeMap::new();
    walk(root, "", &mut groups);
    groups
}

/// Scope string under which this node's children live after
/// normalization. Mirrors `normalize_node`'s child-scope computation
/// but operates on already-scoped node IDs.
fn child_scope_of(node: &TreeNode, scope: &str) -> String {
    let is_auto = node.id.starts_with("auto:");
    let is_window = node.type_name == "window";
    if is_window {
        format!("{}#", node.id)
    } else if is_auto || node.id.is_empty() {
        scope.to_string()
    } else {
        node.id.clone()
    }
}

/// Walk the normalized tree and rewrite a11y refs + populate defaults
/// in place.
fn rewrite_a11y_in_place(
    node: &mut TreeNode,
    scope: &str,
    declared: &HashSet<String>,
    radio_groups: &BTreeMap<RadioGroupKey, Vec<String>>,
    warnings: &mut Vec<String>,
    depth: usize,
) {
    if depth > MAX_TREE_DEPTH {
        return;
    }

    let next_scope = child_scope_of(node, scope);
    node.props = apply_a11y_rewrites(node, scope, declared, radio_groups, warnings);
    for child in &mut node.children {
        rewrite_a11y_in_place(
            child,
            &next_scope,
            declared,
            radio_groups,
            warnings,
            depth + 1,
        );
    }
}

/// Build a new Props for `node` with its a11y sub-object rewritten.
///
/// Returns the input node's props unchanged if there is nothing to do.
fn apply_a11y_rewrites(
    node: &TreeNode,
    scope: &str,
    declared: &HashSet<String>,
    radio_groups: &BTreeMap<RadioGroupKey, Vec<String>>,
    warnings: &mut Vec<String>,
) -> plushie_core::protocol::Props {
    let existing_role = node
        .props
        .get_value("a11y")
        .and_then(|v| v.get("role").cloned());
    let inferred_role = if existing_role.is_none() {
        widget_type_to_role(&node.type_name).map(|s| s.to_string())
    } else {
        None
    };

    let radio_ids = if node.type_name == "radio" {
        node.props.get_str("group").and_then(|g| {
            radio_groups
                .get(&(scope.to_string(), g.to_string()))
                .cloned()
        })
    } else {
        None
    };

    let a11y_obj = node
        .props
        .get_value("a11y")
        .and_then(|v| v.as_object().cloned());

    // If the existing a11y is absent AND we have nothing to inject,
    // leave props alone. This keeps untouched nodes bit-identical.
    if a11y_obj.is_none() && inferred_role.is_none() && radio_ids.is_none() {
        return node.props.clone();
    }

    let mut obj = a11y_obj.unwrap_or_default();

    // Inject inferred role if the author didn't set one.
    if let Some(role) = inferred_role {
        obj.entry("role").or_insert(serde_json::Value::String(role));
    }

    // Rewrite single-ID refs.
    for key in [
        "labelled_by",
        "described_by",
        "error_message",
        "active_descendant",
    ] {
        if let Some(v) = obj.get(key).cloned()
            && let Some(s) = v.as_str()
        {
            let rewritten = resolve_ref(s, scope);
            if !declared.contains(&rewritten) && !s.is_empty() {
                warnings.push(format!(
                    "a11y_ref_unresolved: {key}=\"{s}\" on \"{}\" \
                     does not match any declared widget ID",
                    node.id,
                ));
            }
            obj.insert(key.to_string(), serde_json::Value::String(rewritten));
        }
    }

    // Rewrite each element of `radio_group`.
    if let Some(v) = obj.get("radio_group").cloned()
        && let Some(arr) = v.as_array()
    {
        let rewritten: Vec<serde_json::Value> = arr
            .iter()
            .filter_map(|item| item.as_str())
            .map(|s| {
                let r = resolve_ref(s, scope);
                if !declared.contains(&r) && !s.is_empty() {
                    warnings.push(format!(
                        "a11y_ref_unresolved: radio_group member \"{s}\" \
                         on \"{}\" does not match any declared widget ID",
                        node.id,
                    ));
                }
                serde_json::Value::String(r)
            })
            .collect();
        obj.insert(
            "radio_group".to_string(),
            serde_json::Value::Array(rewritten),
        );
    }

    // Populate implicit radio group (authoring via shared `group` prop)
    // only when the author hasn't already set one explicitly.
    if let Some(ids) = radio_ids
        && !obj.contains_key("radio_group")
    {
        let arr: Vec<serde_json::Value> = ids.into_iter().map(serde_json::Value::String).collect();
        obj.insert("radio_group".to_string(), serde_json::Value::Array(arr));
    }

    // Reassemble props with the updated a11y object.
    install_a11y(&node.props, obj)
}

/// Produce a new `Props` value with `a11y` replaced by the given map.
fn install_a11y(
    base: &plushie_core::protocol::Props,
    obj: serde_json::Map<String, serde_json::Value>,
) -> plushie_core::protocol::Props {
    match base {
        plushie_core::protocol::Props::Typed(map) => {
            let mut map = map.clone();
            map.remove("a11y");
            map.insert("a11y", PropValue::from(serde_json::Value::Object(obj)));
            plushie_core::protocol::Props::Typed(map)
        }
        plushie_core::protocol::Props::Wire(v) => {
            let mut v = v.clone();
            if let Some(m) = v.as_object_mut() {
                m.insert("a11y".to_string(), serde_json::Value::Object(obj));
            }
            plushie_core::protocol::Props::Wire(v)
        }
    }
}

/// Rewrite a cross-widget ID reference through the scope-prefix logic.
///
/// The reference shapes recognized (mirrors the ID-prefix rules):
/// - Already-scoped refs (`"window#path"` or `"scope/leaf"`) pass
///   through unchanged.
/// - Bare refs gain the enclosing scope as a prefix.
/// - Empty refs pass through (nothing to resolve).
fn resolve_ref(raw: &str, scope: &str) -> String {
    if raw.is_empty() || scope.is_empty() {
        return raw.to_string();
    }
    if raw.contains('#') || raw.contains('/') {
        // Author provided a pre-scoped ref; leave it alone.
        return raw.to_string();
    }
    if scope.ends_with('#') {
        format!("{scope}{raw}")
    } else {
        format!("{scope}/{raw}")
    }
}

/// Walk the tree, emit `missing_accessible_name` diagnostics for
/// interactive widgets that would render without any name a screen
/// reader can announce.
///
/// Checked widget types:
///
/// - `button`, `pointer_area`: need either a text child, a `label`
///   prop, `a11y.label`, or `a11y.labelled_by`.
/// - `toggler`, `checkbox`: same as above (their native role is
///   announced, but the *name* still needs to come from somewhere).
///
/// Canvas interactive elements have their own diagnostic in
/// `canvas/interaction.rs`; this check skips them.
fn check_missing_accessible_name(node: &TreeNode, warnings: &mut Vec<String>) {
    fn walk(node: &TreeNode, warnings: &mut Vec<String>) {
        if widget_requires_accessible_name(&node.type_name) && !has_accessible_name(node) {
            warnings.push(format!(
                "missing_accessible_name: {type_name} \"{id}\" has no \
                 label, text child, a11y.label, or a11y.labelled_by; \
                 screen readers will announce no name",
                type_name = node.type_name,
                id = node.id,
            ));
        }
        for child in &node.children {
            walk(child, warnings);
        }
    }
    walk(node, warnings);
}

fn widget_requires_accessible_name(type_name: &str) -> bool {
    matches!(
        type_name,
        "button" | "toggler" | "checkbox" | "pointer_area"
    )
}

/// Returns true if the node carries any source of accessible name.
fn has_accessible_name(node: &TreeNode) -> bool {
    // A `label` prop (checkbox / toggler carry their text here).
    if node.props.get_str("label").is_some_and(|s| !s.is_empty()) {
        return true;
    }
    // An a11y override with label or labelled_by.
    if let Some(a11y) = node.props.get_value("a11y") {
        if a11y
            .get("label")
            .and_then(|v| v.as_str())
            .is_some_and(|s| !s.is_empty())
        {
            return true;
        }
        if a11y
            .get("labelled_by")
            .and_then(|v| v.as_str())
            .is_some_and(|s| !s.is_empty())
        {
            return true;
        }
    }
    // A non-empty text child anywhere in the subtree.
    fn has_text_child(n: &TreeNode) -> bool {
        for child in &n.children {
            if child.type_name == "text"
                && child
                    .props
                    .get_str("content")
                    .is_some_and(|s| !s.is_empty())
            {
                return true;
            }
            if has_text_child(child) {
                return true;
            }
        }
        false
    }
    has_text_child(node)
}

/// Built-in widget-type -> accessible-role map.
///
/// Uses the same role-name strings as iced's native `convert_role`
/// mapping so the automation fallback and the AccessKit tree agree.
/// Widgets whose role is context-dependent (e.g. `tooltip`, which
/// the fork models via iced-direct defaults) are omitted so we don't
/// override the author's intent.
fn widget_type_to_role(widget_type: &str) -> Option<&'static str> {
    Some(match widget_type {
        "button" => "button",
        "checkbox" => "check_box",
        "toggler" => "switch",
        "radio" => "radio_button",
        "text_input" => "text_input",
        "text_editor" => "multiline_text_input",
        "text" => "label",
        "rich_text" => "label",
        "slider" => "slider",
        "vertical_slider" => "slider",
        "pick_list" => "combo_box",
        "combo_box" => "combo_box",
        "progress_bar" => "progress_indicator",
        "image" => "image",
        "svg" => "image",
        "qr_code" => "image",
        "scrollable" => "scroll_view",
        "container" => "group",
        "column" => "group",
        "row" => "group",
        "stack" => "group",
        "grid" => "group",
        "pane_grid" => "group",
        "table" => "table",
        "canvas" => "canvas",
        "rule" => "separator",
        // Space is purely visual whitespace. No accessible role.
        // Tooltip, overlay, pin, floating, sensor, pointer_area,
        // themer, responsive, window: no default role; leave them
        // to the fork or explicit overrides.
        _ => return None,
    })
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    /// Normalize a tree through both the scope-rewrite transform and
    /// the memo cache, so tests can assert memo-hit behaviour.
    fn normalize_with_memo(
        tree: &TreeNode,
        cache: &mut super::super::memo_cache::MemoCache,
    ) -> (TreeNode, Vec<String>) {
        cache.begin_cycle();
        let mut result = tree.clone();
        let mut transform = NormalizeTransform::with_memo_cache(Some(cache));
        let mut ctx = WalkCtx::default();
        walk(&mut result, &mut [&mut transform], &mut ctx);
        drop(transform);
        cache.finish_cycle();
        let (warnings, _ctx) = finalize_a11y(&mut result, ctx);
        (result, warnings)
    }

    fn memo_node(key: &str, deps_hash: u64, inner: TreeNode) -> TreeNode {
        let mut props = plushie_core::protocol::PropMap::new();
        props.insert("__memo_deps__", deps_hash);
        TreeNode {
            id: format!("memo:{key}"),
            type_name: "__memo__".to_string(),
            props: plushie_core::protocol::Props::Typed(props),
            children: vec![inner],
        }
    }

    #[test]
    fn memo_hit_reuses_cached_subtree() {
        use super::super::memo_cache::MemoCache;
        let mut cache = MemoCache::new();

        // First render: miss, populates the cache.
        let tree1 = node(
            "root",
            "column",
            vec![memo_node(
                "hdr",
                42,
                node("inner", "text", vec![node("leaf", "text", vec![])]),
            )],
        );
        let (out1, _warn1) = normalize_with_memo(&tree1, &mut cache);
        let memo1 = &out1.children[0];
        // memo id got scope-prefixed into root's scope.
        assert_eq!(memo1.id, "root/memo:hdr");
        assert_eq!(memo1.children[0].id, "root/memo:hdr/inner");
        assert_eq!(memo1.children[0].children[0].id, "root/memo:hdr/inner/leaf");

        // Second render: same deps hash, different inner contents.
        // The hit should restore the cached inner, ignoring the
        // freshly-authored tree.
        let tree2 = node(
            "root",
            "column",
            vec![memo_node(
                "hdr",
                42,
                node("different", "text", vec![node("leaf2", "text", vec![])]),
            )],
        );
        let (out2, _warn2) = normalize_with_memo(&tree2, &mut cache);
        let memo2 = &out2.children[0];
        assert_eq!(memo2.id, "root/memo:hdr");
        // Cache hit restored the earlier "inner" subtree.
        assert_eq!(memo2.children[0].id, "root/memo:hdr/inner");
    }

    #[test]
    fn memo_miss_on_deps_change_renormalizes() {
        use super::super::memo_cache::MemoCache;
        let mut cache = MemoCache::new();

        let tree1 = node(
            "root",
            "column",
            vec![memo_node("hdr", 1, node("inner_a", "text", vec![]))],
        );
        let (_out1, _w1) = normalize_with_memo(&tree1, &mut cache);

        // Deps change: the freshly-authored subtree should appear,
        // not the cached one.
        let tree2 = node(
            "root",
            "column",
            vec![memo_node("hdr", 2, node("inner_b", "text", vec![]))],
        );
        let (out2, _w2) = normalize_with_memo(&tree2, &mut cache);
        assert_eq!(out2.children[0].children[0].id, "root/memo:hdr/inner_b");
    }

    #[test]
    fn nested_memos_each_memoize_independently() {
        use super::super::memo_cache::MemoCache;
        let mut cache = MemoCache::new();

        let inner_memo = memo_node("inner", 10, node("leaf", "text", vec![]));
        let outer_memo = memo_node("outer", 20, inner_memo);
        let tree1 = node("root", "column", vec![outer_memo]);
        let (out1, _w1) = normalize_with_memo(&tree1, &mut cache);
        let outer1 = &out1.children[0];
        assert_eq!(outer1.id, "root/memo:outer");
        let inner1 = &outer1.children[0];
        assert_eq!(inner1.id, "root/memo:outer/memo:inner");
        assert_eq!(inner1.children[0].id, "root/memo:outer/memo:inner/leaf");

        // Second render: both hit.
        let inner_memo2 = memo_node("inner", 10, node("other_leaf", "text", vec![]));
        let outer_memo2 = memo_node("outer", 20, inner_memo2);
        let tree2 = node("root", "column", vec![outer_memo2]);
        let (out2, _w2) = normalize_with_memo(&tree2, &mut cache);
        let outer2 = &out2.children[0];
        let inner2 = &outer2.children[0];
        // The cached outer returns the cached inner subtree with
        // `leaf`, not `other_leaf`.
        assert_eq!(inner2.children[0].id, "root/memo:outer/memo:inner/leaf");
    }

    fn node(id: &str, type_name: &str, children: Vec<TreeNode>) -> TreeNode {
        TreeNode {
            id: id.to_string(),
            type_name: type_name.to_string(),
            props: json!({}).into(),
            children,
        }
    }

    fn node_with_props(id: &str, type_name: &str, props: serde_json::Value) -> TreeNode {
        TreeNode {
            id: id.to_string(),
            type_name: type_name.to_string(),
            props: props.into(),
            children: vec![],
        }
    }

    #[test]
    fn scope_buffer_survives_deep_nesting() {
        // Regression: the scope-string buffer threaded through
        // normalize_node's walk must grow on enter and shrink on
        // exit so siblings at the same depth see the same scope
        // regardless of traversal order.
        let tree = node(
            "main",
            "window",
            vec![
                node(
                    "form",
                    "container",
                    vec![
                        node("a", "text_input", vec![]),
                        node(
                            "row",
                            "row",
                            vec![
                                node("b", "text_input", vec![]),
                                node("c", "text_input", vec![]),
                            ],
                        ),
                        node("d", "text_input", vec![]),
                    ],
                ),
                node("footer", "container", vec![node("e", "text", vec![])]),
            ],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty(), "got {warnings:?}");
        let form = &result.children[0];
        assert_eq!(form.id, "main#form");
        assert_eq!(form.children[0].id, "main#form/a");
        let row = &form.children[1];
        assert_eq!(row.id, "main#form/row");
        assert_eq!(row.children[0].id, "main#form/row/b");
        assert_eq!(row.children[1].id, "main#form/row/c");
        // `d` at the same depth as `row` must see the scope restored
        // after `row`'s exit - not leak "/row".
        assert_eq!(form.children[2].id, "main#form/d");
        let footer = &result.children[1];
        assert_eq!(footer.id, "main#footer");
        assert_eq!(footer.children[0].id, "main#footer/e");
    }

    #[test]
    fn normalize_is_deterministic_across_runs() {
        // Same input tree twice through normalize must yield the same
        // normalized ID shape. Guards the scope buffer against leaking
        // state across calls.
        let build = || {
            node(
                "main",
                "window",
                vec![node(
                    "form",
                    "container",
                    vec![
                        node("a", "text_input", vec![]),
                        node("b", "text_input", vec![]),
                    ],
                )],
            )
        };
        let (a, _) = normalize(&build());
        let (b, _) = normalize(&build());
        let collect_ids = |n: &TreeNode, out: &mut Vec<String>| {
            fn walk(n: &TreeNode, out: &mut Vec<String>) {
                out.push(n.id.clone());
                for c in &n.children {
                    walk(c, out);
                }
            }
            walk(n, out);
        };
        let mut a_ids = Vec::new();
        let mut b_ids = Vec::new();
        collect_ids(&a, &mut a_ids);
        collect_ids(&b, &mut b_ids);
        assert_eq!(a_ids, b_ids);
    }

    #[test]
    fn flat_tree_preserves_ids() {
        let tree = node(
            "root",
            "column",
            vec![node("a", "text", vec![]), node("b", "text", vec![])],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.children[0].id, "root/a");
        assert_eq!(result.children[1].id, "root/b");
    }

    #[test]
    fn auto_ids_are_not_scoped() {
        let tree = node(
            "auto:col:1:1",
            "column",
            vec![node("btn", "button", vec![])],
        );
        let (result, warnings) = normalize(&tree);
        // The unnamed button triggers missing_accessible_name; that's
        // expected given no label/text child, and is the only warning.
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("missing_accessible_name"));
        assert_eq!(result.children[0].id, "btn");
    }

    #[test]
    fn nested_scoping() {
        let tree = node(
            "form",
            "container",
            vec![node(
                "section",
                "column",
                vec![node("field", "text_input", vec![])],
            )],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.children[0].id, "form/section");
        assert_eq!(result.children[0].children[0].id, "form/section/field");
    }

    #[test]
    fn window_scopes_children_with_hash() {
        let tree = node("main", "window", vec![node("col", "column", vec![])]);
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.id, "main");
        assert_eq!(result.children[0].id, "main#col");
    }

    #[test]
    fn window_nested_children_use_slash_after_hash() {
        let tree = node(
            "main",
            "window",
            vec![node(
                "form",
                "container",
                vec![node("email", "text_input", vec![])],
            )],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.children[0].id, "main#form");
        assert_eq!(result.children[0].children[0].id, "main#form/email");
    }

    #[test]
    fn hash_in_id_produces_warning() {
        let tree = node("bad#id", "text", vec![]);
        let (_, warnings) = normalize(&tree);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("reserved character '#'"));
    }

    #[test]
    fn duplicate_ids_produce_warning() {
        let tree = node(
            "root",
            "column",
            vec![node("btn", "button", vec![]), node("btn", "button", vec![])],
        );
        let (_, warnings) = normalize(&tree);
        // Two unnamed buttons also trigger missing_accessible_name.
        assert!(warnings.iter().any(|w| w.contains("duplicate ID")));
    }

    #[test]
    fn reserved_slash_in_id_produces_warning() {
        let tree = node("form/field", "text_input", vec![]);
        let (_, warnings) = normalize(&tree);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("reserved character"));
    }

    #[test]
    fn excessive_depth_is_truncated_with_diagnostic() {
        // Build a tree deeper than MAX_TREE_DEPTH. The walker enforces
        // the cap and emits tree_depth_exceeded at the boundary; the
        // normalize pass must not stack-overflow in the process.
        let mut tree = node("leaf", "text", vec![]);
        for i in 0..(MAX_TREE_DEPTH + 20) {
            tree = node(&format!("n{i}"), "container", vec![tree]);
        }

        let (_result, warnings) = normalize(&tree);
        assert!(
            warnings.iter().any(|w| w.contains("tree_depth_exceeded")),
            "expected tree_depth_exceeded diagnostic; got {warnings:?}"
        );
    }

    #[test]
    fn auto_ids_skip_duplicate_check() {
        let tree = node(
            "root",
            "column",
            vec![
                node("auto:text:1:1", "text", vec![]),
                node("auto:text:1:1", "text", vec![]),
            ],
        );
        let (_, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
    }

    // -- A11y rewrite tests -------------------------------------------------

    #[test]
    fn a11y_role_populated_from_widget_type() {
        let tree = node(
            "root",
            "column",
            vec![node_with_props("save", "button", json!({}))],
        );
        let (result, _warnings) = normalize(&tree);
        let btn = &result.children[0];
        let role = btn
            .props
            .get_value("a11y")
            .and_then(|v| v.get("role").and_then(|r| r.as_str()).map(str::to_string));
        assert_eq!(role.as_deref(), Some("button"));
    }

    #[test]
    fn a11y_role_explicit_wins_over_inferred() {
        let tree = node(
            "root",
            "column",
            vec![node_with_props(
                "save",
                "button",
                json!({"a11y": {"role": "link"}}),
            )],
        );
        let (result, _warnings) = normalize(&tree);
        let btn = &result.children[0];
        let role = btn
            .props
            .get_value("a11y")
            .and_then(|v| v.get("role").and_then(|r| r.as_str()).map(str::to_string));
        assert_eq!(role.as_deref(), Some("link"));
    }

    #[test]
    fn a11y_ref_rewritten_inside_scoped_container() {
        let tree = node(
            "form",
            "container",
            vec![
                node_with_props("heading", "text", json!({"content": "Log in"})),
                node_with_props(
                    "email",
                    "text_input",
                    json!({"a11y": {"labelled_by": "heading"}}),
                ),
            ],
        );
        let (result, warnings) = normalize(&tree);
        assert!(
            warnings.is_empty(),
            "no diagnostics expected, got {warnings:?}"
        );
        let email = &result.children[1];
        let labelled_by = email.props.get_value("a11y").and_then(|v| {
            v.get("labelled_by")
                .and_then(|r| r.as_str())
                .map(str::to_string)
        });
        assert_eq!(labelled_by.as_deref(), Some("form/heading"));
    }

    #[test]
    fn a11y_ref_unresolved_emits_diagnostic() {
        let tree = node(
            "form",
            "container",
            vec![node_with_props(
                "email",
                "text_input",
                json!({"a11y": {"labelled_by": "missing"}}),
            )],
        );
        let (_result, warnings) = normalize(&tree);
        assert!(
            warnings.iter().any(|w| w.contains("a11y_ref_unresolved")),
            "expected a11y_ref_unresolved diagnostic, got {warnings:?}"
        );
    }

    #[test]
    fn implicit_radio_group_populates_radio_group_a11y() {
        let tree = node(
            "form",
            "container",
            vec![
                node_with_props("r1", "radio", json!({"group": "flavor"})),
                node_with_props("r2", "radio", json!({"group": "flavor"})),
                node_with_props("r3", "radio", json!({"group": "flavor"})),
            ],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty(), "got {warnings:?}");
        for child in &result.children {
            let group = child
                .props
                .get_value("a11y")
                .and_then(|v| v.get("radio_group").cloned())
                .and_then(|v| v.as_array().cloned());
            let group = group.expect("radio_group should be populated");
            let ids: Vec<String> = group
                .iter()
                .filter_map(|v| v.as_str().map(str::to_string))
                .collect();
            assert_eq!(ids, vec!["form/r1", "form/r2", "form/r3"]);
        }
    }

    #[test]
    fn missing_accessible_name_diagnostic_for_icon_only_button() {
        let tree = node("root", "column", vec![node("save", "button", vec![])]);
        let (_result, warnings) = normalize(&tree);
        assert!(
            warnings
                .iter()
                .any(|w| w.contains("missing_accessible_name") && w.contains("save")),
            "expected missing_accessible_name for icon-only button, got {warnings:?}"
        );
    }

    #[test]
    fn button_with_text_child_does_not_warn() {
        let text_child = TreeNode {
            id: "auto:text:1".to_string(),
            type_name: "text".to_string(),
            props: json!({"content": "Save"}).into(),
            children: vec![],
        };
        let button = TreeNode {
            id: "save".to_string(),
            type_name: "button".to_string(),
            props: json!({}).into(),
            children: vec![text_child],
        };
        let tree = node("root", "column", vec![button]);
        let (_result, warnings) = normalize(&tree);
        assert!(
            warnings.is_empty(),
            "button with text child should be named; got {warnings:?}"
        );
    }

    #[test]
    fn checkbox_with_label_prop_does_not_warn() {
        let tree = node(
            "root",
            "column",
            vec![node_with_props(
                "agree",
                "checkbox",
                json!({"label": "I agree", "checked": false}),
            )],
        );
        let (_result, warnings) = normalize(&tree);
        assert!(warnings.is_empty(), "got {warnings:?}");
    }

    #[test]
    fn explicit_radio_group_is_not_overwritten_but_rewritten() {
        let tree = node(
            "form",
            "container",
            vec![
                node_with_props("heading", "text", json!({"content": "Pick"})),
                node_with_props(
                    "r1",
                    "radio",
                    json!({
                        "group": "flavor",
                        "a11y": {"radio_group": ["heading"]}
                    }),
                ),
            ],
        );
        let (result, warnings) = normalize(&tree);
        // No diagnostic since `heading` is a real declared ID.
        assert!(warnings.is_empty(), "got {warnings:?}");
        let r1 = &result.children[1];
        let group = r1
            .props
            .get_value("a11y")
            .and_then(|v| v.get("radio_group").cloned())
            .and_then(|v| v.as_array().cloned())
            .unwrap();
        let ids: Vec<String> = group
            .iter()
            .filter_map(|v| v.as_str().map(str::to_string))
            .collect();
        assert_eq!(ids, vec!["form/heading"]);
    }
}
