//! Tree normalization: scope prefixing and ID validation.
//!
//! After `App::view()` returns a `View` (TreeNode), normalization
//! walks the tree to apply scoped ID prefixes and validate ID
//! constraints.
//!
//! ## Scoping rules
//!
//! Containers with explicit (non-auto) IDs create a scope. Their
//! children's IDs are prefixed with the scope chain joined by `/`.
//! Two node types are exempt:
//!
//! - **Auto IDs** (prefixed `auto:`): generated by the DSL, not
//!   user-chosen. They don't participate in scoping and bypass
//!   duplicate detection (the same call site in a loop produces
//!   identical auto IDs).
//! - **Window nodes** (`type_name == "window"`): top-level layout
//!   containers that don't scope their children.
//!
//! ## ID constraints
//!
//! - `/` is reserved as the scope separator and rejected in
//!   user-provided IDs.
//! - Duplicate explicit IDs within a tree produce a warning.
//!
//! ## Depth cap
//!
//! Recursion is capped at
//! [`plushie_widget_sdk::shared_state::MAX_TREE_DEPTH`]. Beyond the
//! cap the subtree is truncated (the returned node has no children)
//! and a `tree_too_deep` diagnostic is appended. Render and
//! prepare_walk apply the same cap so defence-in-depth holds even
//! if the host sends a pathologically nested tree.

use std::collections::HashSet;

use plushie_core::protocol::TreeNode;
use plushie_widget_sdk::shared_state::MAX_TREE_DEPTH;

/// Normalize a view tree: apply scope prefixes and validate IDs.
///
/// Returns the normalized tree and any validation warnings
/// (duplicate IDs, reserved characters).
pub fn normalize(tree: &TreeNode) -> (TreeNode, Vec<String>) {
    let mut warnings = Vec::new();
    let mut seen_ids = HashSet::new();
    let result = normalize_node(tree, "", &mut seen_ids, &mut warnings, 0);
    (result, warnings)
}

fn normalize_node(
    node: &TreeNode,
    scope: &str,
    seen_ids: &mut HashSet<String>,
    warnings: &mut Vec<String>,
    depth: usize,
) -> TreeNode {
    if depth > MAX_TREE_DEPTH {
        // Truncate the subtree to stop runaway recursion. The current
        // node is returned with no children; a diagnostic records the
        // truncation so hosts can surface it.
        log::error!(
            "[code=tree_too_deep][id={}] normalize depth exceeds {}, truncating subtree",
            node.id,
            MAX_TREE_DEPTH
        );
        warnings.push(format!(
            "tree_too_deep: subtree rooted at \"{}\" exceeds MAX_TREE_DEPTH={}, truncating",
            node.id, MAX_TREE_DEPTH
        ));
        return TreeNode {
            id: node.id.clone(),
            type_name: node.type_name.clone(),
            props: node.props.clone(),
            children: vec![],
        };
    }
    let id = &node.id;
    let type_name = &node.type_name;

    let is_auto = id.starts_with("auto:");
    let is_window = type_name == "window";

    // Build the scoped ID.
    // Window nodes keep their bare ID. Children of windows get "window#id".
    // Deeper descendants get "window#parent/id" (# only at window boundary).
    let scoped_id = if is_auto || scope.is_empty() {
        id.clone()
    } else if scope.ends_with('#') {
        format!("{scope}{id}")
    } else {
        format!("{scope}/{id}")
    };

    // Check for duplicate IDs (only for non-auto IDs).
    if !is_auto && !scoped_id.is_empty() && !seen_ids.insert(scoped_id.clone()) {
        warnings.push(format!("duplicate ID: \"{scoped_id}\""));
    }

    // Check for reserved characters in user-provided IDs.
    if !is_auto {
        if id.contains('/') {
            warnings.push(format!(
                "ID \"{id}\" contains reserved character '/'. \
                 Use container scoping instead."
            ));
        }
        if id.contains('#') {
            warnings.push(format!(
                "ID \"{id}\" contains reserved character '#'. \
                 '#' is reserved for window-qualified paths."
            ));
        }
    }

    // Build the scope for children.
    // Window nodes set "window#" as the child scope.
    // Named non-window nodes propagate their scoped ID.
    // Auto-ID nodes are transparent.
    let child_scope = if is_window {
        format!("{scoped_id}#")
    } else if is_auto || id.is_empty() {
        scope.to_string()
    } else {
        scoped_id.clone()
    };

    // Normalize children recursively.
    let children = node
        .children
        .iter()
        .map(|child| normalize_node(child, &child_scope, seen_ids, warnings, depth + 1))
        .collect();

    TreeNode {
        id: scoped_id,
        type_name: node.type_name.clone(),
        props: node.props.clone(),
        children,
    }
}

#[cfg(test)]
mod tests {
    use super::*;
    use serde_json::json;

    fn node(id: &str, type_name: &str, children: Vec<TreeNode>) -> TreeNode {
        TreeNode {
            id: id.to_string(),
            type_name: type_name.to_string(),
            props: json!({}).into(),
            children,
        }
    }

    #[test]
    fn flat_tree_preserves_ids() {
        let tree = node(
            "root",
            "column",
            vec![node("a", "text", vec![]), node("b", "text", vec![])],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.children[0].id, "root/a");
        assert_eq!(result.children[1].id, "root/b");
    }

    #[test]
    fn auto_ids_are_not_scoped() {
        let tree = node(
            "auto:col:1:1",
            "column",
            vec![node("btn", "button", vec![])],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.children[0].id, "btn");
    }

    #[test]
    fn nested_scoping() {
        let tree = node(
            "form",
            "container",
            vec![node(
                "section",
                "column",
                vec![node("field", "text_input", vec![])],
            )],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.children[0].id, "form/section");
        assert_eq!(result.children[0].children[0].id, "form/section/field");
    }

    #[test]
    fn window_scopes_children_with_hash() {
        let tree = node("main", "window", vec![node("col", "column", vec![])]);
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.id, "main");
        assert_eq!(result.children[0].id, "main#col");
    }

    #[test]
    fn window_nested_children_use_slash_after_hash() {
        let tree = node(
            "main",
            "window",
            vec![node(
                "form",
                "container",
                vec![node("email", "text_input", vec![])],
            )],
        );
        let (result, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
        assert_eq!(result.children[0].id, "main#form");
        assert_eq!(result.children[0].children[0].id, "main#form/email");
    }

    #[test]
    fn hash_in_id_produces_warning() {
        let tree = node("bad#id", "text", vec![]);
        let (_, warnings) = normalize(&tree);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("reserved character '#'"));
    }

    #[test]
    fn duplicate_ids_produce_warning() {
        let tree = node(
            "root",
            "column",
            vec![node("btn", "button", vec![]), node("btn", "button", vec![])],
        );
        let (_, warnings) = normalize(&tree);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("duplicate ID"));
    }

    #[test]
    fn reserved_slash_in_id_produces_warning() {
        let tree = node("form/field", "text_input", vec![]);
        let (_, warnings) = normalize(&tree);
        assert_eq!(warnings.len(), 1);
        assert!(warnings[0].contains("reserved character"));
    }

    #[test]
    fn excessive_depth_is_truncated_with_diagnostic() {
        // Build a tree deeper than MAX_TREE_DEPTH. The normalize pass
        // must not stack-overflow and must emit a tree_too_deep
        // diagnostic at the cap boundary.
        let mut tree = node("leaf", "text", vec![]);
        for i in 0..(MAX_TREE_DEPTH + 20) {
            tree = node(&format!("n{i}"), "container", vec![tree]);
        }

        let (_result, warnings) = normalize(&tree);
        assert!(
            warnings.iter().any(|w| w.contains("tree_too_deep")),
            "expected tree_too_deep diagnostic; got {warnings:?}"
        );
    }

    #[test]
    fn auto_ids_skip_duplicate_check() {
        let tree = node(
            "root",
            "column",
            vec![
                node("auto:text:1:1", "text", vec![]),
                node("auto:text:1:1", "text", vec![]),
            ],
        );
        let (_, warnings) = normalize(&tree);
        assert!(warnings.is_empty());
    }
}
