//! Typed pointer event data for the wire protocol.
//!
//! These structs represent the data payload of pointer and viewport
//! events. They are shared between the SDK (which parses them from
//! wire JSON) and could be used by the renderer to construct events
//! with typed fields.

use crate::key::{MouseButton, PointerKind};
use crate::protocol::KeyModifiers;

/// Data from a pointer press event (mouse button down, touch start).
#[derive(Debug, Clone)]
pub struct PointerPress {
    pub x: f32,
    pub y: f32,
    pub button: MouseButton,
    pub pointer: PointerKind,
    pub finger: Option<u64>,
    pub modifiers: KeyModifiers,
}

/// Data from a pointer release event (mouse button up, touch end).
#[derive(Debug, Clone)]
pub struct PointerRelease {
    pub x: f32,
    pub y: f32,
    pub button: MouseButton,
    pub pointer: PointerKind,
    pub finger: Option<u64>,
    pub modifiers: KeyModifiers,
}

/// Data from a pointer move event.
#[derive(Debug, Clone)]
pub struct PointerMove {
    pub x: f32,
    pub y: f32,
    pub pointer: PointerKind,
    pub finger: Option<u64>,
    pub modifiers: KeyModifiers,
}

/// Data from a raw scroll input event (mouse wheel, trackpad).
///
/// Distinct from [`ScrollPosition`] which reports where a scrollable
/// widget's viewport ended up. This reports the raw pointer input.
#[derive(Debug, Clone)]
pub struct PointerScroll {
    pub x: f32,
    pub y: f32,
    pub delta_x: f32,
    pub delta_y: f32,
    pub pointer: PointerKind,
    pub modifiers: KeyModifiers,
}

/// Data from a drag event.
#[derive(Debug, Clone)]
pub struct PointerDrag {
    pub x: f32,
    pub y: f32,
    pub pointer: PointerKind,
    pub modifiers: KeyModifiers,
}

/// Viewport state from a scrollable widget's "scrolled" event.
///
/// Reports where the scrollable viewport ended up after scrolling.
/// Distinct from [`PointerScroll`] which reports raw wheel input.
#[derive(Debug, Clone)]
pub struct ScrollPosition {
    pub absolute_x: f32,
    pub absolute_y: f32,
    pub relative_x: f32,
    pub relative_y: f32,
    pub bounds_width: f32,
    pub bounds_height: f32,
    pub content_width: f32,
    pub content_height: f32,
}

/// Data from a widget-level key press or release event.
#[derive(Debug, Clone)]
pub struct KeyData {
    /// Logical key name (e.g., "a", "Enter", "ArrowUp").
    pub key: String,
    /// Key after modifier application (e.g., "A" when Shift+a).
    pub modified_key: Option<String>,
    /// Physical key code (layout-independent).
    pub physical_key: Option<String>,
    pub modifiers: KeyModifiers,
    /// Text generated by the key press, if any.
    pub text: Option<String>,
    /// Whether this is an auto-repeat event.
    pub repeat: bool,
}

/// Data from a window or widget resize event.
#[derive(Debug, Clone, Copy)]
pub struct ResizeDimensions {
    pub width: f32,
    pub height: f32,
}
